#ifndef PROJKT_SENS_WEATHER_APP_SRC_MAIN_CPP_APP_H_
#define PROJKT_SENS_WEATHER_APP_SRC_MAIN_CPP_APP_H_

#include <jni.h>

jint JNI_OnLoad(JavaVM* vm, void*);

#endif //PROJKT_SENS_WEATHER_APP_SRC_MAIN_CPP_APP_H_
